let allMusic = [
  {
    name: "Shape-of-You",
    artist: "Ed Sheeran",
    img: "music-1",
    src: "music-1",
  },
  {
    name: "Calm-Down",
    artist: "Rema, Selena Gomez",
    img: "music-2",
    src: "music-2",
  },
  {
    name: "Let Me Down Slowly",
    artist: "Alec Benjamin",
    img: "music-3",
    src: "music-3",
  },
  {
    name: "Love Me Like You Do",
    artist: "Ellie Goulding",
    img: "music-4",
    src: "music-4",
  },
  {
    name: "Starboy",
    artist: "The Weeknd",
    img: "music-5",
    src: "music-5",
  },
  {
    name: "Girls Like You",
    artist: "Maroon 5",
    img: "music-6",
    src: "music-6",
  },
  {
    name: "On My Way",
    artist: "Alan Walker",
    img: "music-7",
    src: "music-7",
  },
  {
    name: "Sorry",
    artist: "Justin Beiber",
    img: "music-8",
    src: "music-8",
  },
  {
    name: "Sugar and Brownies",
    artist: "Dharia",
    img: "music-9",
    src: "music-9",
  },
  {
    name: "Faded",
    artist: "Alan Walker",
    img: "music-10",
    src: "music-10",
  },
  {
    name: "Boyz With Fun",
    artist: "BTS",
    img: "music-11",
    src: "music-11",
  },
  {
    name: "Black Swan",
    artist: "BTS",
    img: "music-12",
    src: "music-12",
  },
  {
    name: "Under the Influence",
    artist: "Chris Brown",
    img: "music-13",
    src: "music-13",
  },
  {
    name: "Mic Drop",
    artist: "BTS",
    img: "music-14",
    src: "music-14",
  },
  {
    name: "ON",
    artist: "BTS",
    img: "music-15",
    src: "music-15",
  },
  {
    name: "Flowers",
    artist: "MIley Cyru",
    img: "music-16",
    src: "music-16",
  },
  {
    name: "How You Like That",
    artist: "BLACKPINK",
    img: "music-17",
    src: "music-17",
  },
  {
    name: "Permission to Dance",
    artist: "BTS",
    img: "music-18",
    src: "music-18",
  },
  {
    name: "IDOL",
    artist: "BTS",
    img: "music-19",
    src: "music-19",
  },
  {
    name: "Kill This Love",
    artist: "BLACKPINK",
    img: "music-20",
    src: "music-20",
  },
  {
    name: "Make It Right",
    artist: "BTS",
    img: "music-21",
    src: "music-21",
  },
  {
    name: "Paint The Town Red",
    artist: "Doja Cat",
    img: "music-22",
    src: "music-22",
  },
  {
    name: "New Rules",
    artist: "Dus Lipa",
    img: "music-23",
    src: "music-23",
  },
  {
    name: "Blood, Sweat & Tears",
    artist: "BTS",
    img: "music-24",
    src: "music-24",
  },
  {
    name: "Save Me",
    artist: "BTS",
    img: "music-25",
    src: "music-25",
  },
  {
    name: "Life Goes On",
    artist: "BTS",
    img: "music-26",
    src: "music-26",
  },
  {
    name: "Spring Day",
    artist: "BTS",
    img: "music-27",
    src: "music-27",
  },
  {
    name: "Renegade X Under the Influence",
    artist: "",
    img: "music-28",
    src: "music-28",
  },
];
